name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        php-versions: ['8.2', '8.3']

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: posix, pcntl
          tools: composer:v2

      - name: Composer install
        run: composer install

      - name: Codestyle checks
        run: vendor/bin/php-cs-fixer fix -v --dry-run

      - name: Static analyze
        run: vendor/bin/psalm

      - name: Run tests
        run: vendor/bin/phpunit
